import { describe, expect, test } from "bun:test";
import { claudeOpusGeneration } from "../scripts/generate-models";
import { Effort } from "../src/model-thinking";
import { getBundledModel, getBundledModels, getBundledProviders } from "../src/models";

describe("preset catalog model entries", () => {
	test("bundles xai/grok-4.7 with vision and supported reasoning levels", () => {
		const model = getBundledModel("xai", "grok-4.7");

		expect(model.api).toBe("openai-completions");
		expect(model.baseUrl).toBe("https://api.x.ai/v1");
		expect(model.input).toEqual(["text", "image"]);
		expect(model.reasoning).toBe(true);
		expect(model.contextWindow).toBe(500_000);
		expect(model.maxTokens).toBe(500_000);
		expect(model.cost).toEqual({ input: 2, output: 6, cacheRead: 0.5, cacheWrite: 0 });
		expect(model.thinking).toEqual({
			mode: "effort",
			minLevel: Effort.Low,
			maxLevel: Effort.XHigh,
			defaultLevel: Effort.High,
		});
	});
	test("bundles anthropic/claude-opus-5-5 with vision and adaptive thinking", () => {
		const model = getBundledModel("anthropic", "claude-opus-5-5");

		expect(model.id).toBe("claude-opus-5-5");
		expect(model.provider).toBe("anthropic");
		expect(model.api).toBe("anthropic-messages");
		expect(model.baseUrl).toBe("https://api.anthropic.com");
		expect(model.input).toEqual(["text", "image"]);
		expect(model.reasoning).toBe(true);
		expect(model.contextWindow).toBe(1_000_000);
		expect(model.maxTokens).toBe(128_000);
		expect(model.cost).toEqual({ input: 4, output: 20, cacheRead: 0.2, cacheWrite: 5 });
		expect(model.thinking).toEqual({
			mode: "anthropic-adaptive",
			minLevel: Effort.Minimal,
			maxLevel: Effort.Max,
		});
	});
	test("bundles kimi-code/kimi-k2.7-code", () => {
		const model = getBundledModel("kimi-code", "kimi-k2.7-code");

		expect(model.id).toBe("kimi-k2.7-code");
		expect(model.provider).toBe("kimi-code");
		expect(model.name).toBe("Kimi K2.7 Code");
		expect(model.reasoning).toBe(true);
		expect(model.input).toContain("text");
		expect(model.thinking).toEqual({ mode: "effort", minLevel: Effort.Minimal, maxLevel: Effort.High });
	});

	test("bundles zai/glm-5.3 flagship", () => {
		const model = getBundledModel("zai", "glm-5.3");

		expect(model.id).toBe("glm-5.3");
		expect(model.provider).toBe("zai");
		expect(model.name).toBe("GLM-5.3");
		expect(model.reasoning).toBe(true);
		expect(model.input).toContain("text");
		expect(model.contextWindow).toBe(1_000_000);
		expect(model.maxTokens).toBe(131_072);
		expect(model.thinking).toEqual({ mode: "budget", minLevel: Effort.Minimal, maxLevel: Effort.XHigh });
	});

	test("bundles google-gemini-cli/gemini-3.5-flash", () => {
		const model = getBundledModel("google-gemini-cli", "gemini-3.5-flash");

		expect(model.id).toBe("gemini-3.5-flash");
		expect(model.provider).toBe("google-gemini-cli");
		expect(model.api).toBe("google-gemini-cli");
		expect(model.baseUrl).toBe("https://cloudcode-pa.googleapis.com");
		expect(model.name).toBe("Gemini 3.5 Flash");
		expect(model.reasoning).toBe(true);
		expect(model.input).toContain("image");
		expect(model.contextWindow).toBe(1_048_576);
		expect(model.maxTokens).toBe(65_536);
		expect(model.thinking).toEqual({ mode: "google-level", minLevel: Effort.Minimal, maxLevel: Effort.High });
	});

	test("bundles minimax-code/minimax-v3", () => {
		const model = getBundledModel("minimax-code", "minimax-v3");

		expect(model.id).toBe("minimax-v3");
		expect(model.provider).toBe("minimax-code");
		expect(model.name).toBe("MiniMax-V3");
		expect(model.reasoning).toBe(true);
		expect(model.contextWindow).toBe(512_000);
		expect(model.maxTokens).toBe(128_000);
		expect(model.thinking).toEqual({ mode: "effort", minLevel: Effort.Minimal, maxLevel: Effort.High });
	});
});

/**
 * Opus 5.5 shipped in the bundled catalog for `anthropic` only, so anybody
 * reaching Anthropic through a gateway (Bedrock, OpenRouter, Copilot, Vercel,
 * Kilo, Venice, OpenCode Zen, Cloudflare) saw no Opus 5.5 row in `/model` even
 * after the preset landed. The catalog is regenerated by hand, so nothing
 * failed when upstream published the model for those providers and the bundled
 * copy stayed behind. Pin the parity instead: a provider that serves Opus 5
 * serves Opus 5.5.
 */
describe("Claude Opus 5.5 provider coverage", () => {
	function providersBundlingOpusGeneration(generation: number): string[] {
		const providers: string[] = [];
		for (const provider of getBundledProviders()) {
			const models = getBundledModels(provider as Parameters<typeof getBundledModels>[0]);
			if (models.some(model => claudeOpusGeneration(model.id) === generation)) providers.push(provider);
		}
		return providers.sort();
	}

	test("every provider that bundles Opus 5 also bundles Opus 5.5", () => {
		const opus5Providers = providersBundlingOpusGeneration(5);
		// Guards against the check going vacuous if id parsing or the catalog drifts.
		expect(opus5Providers.length).toBeGreaterThan(1);
		const opus55Providers = new Set(providersBundlingOpusGeneration(5.5));
		expect(opus5Providers.filter(provider => !opus55Providers.has(provider))).toEqual([]);
	});

	test("Bedrock bundles Opus 5.5 in every region it bundles Opus 5 in", () => {
		const regionsFor = (generation: number): string[] =>
			getBundledModels("amazon-bedrock")
				.filter(model => claudeOpusGeneration(model.id) === generation)
				.map(model => model.id.replace(/anthropic\.claude-opus-5(-5)?$/, "anthropic"))
				.sort();

		expect(regionsFor(5).length).toBeGreaterThan(1);
		expect(regionsFor(5.5)).toEqual(regionsFor(5));
	});
});
